---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("tidyverse");
# install.packages("rgdal");
library(tidyverse)
require("maps")
library(geosphere)
library(stringr)
library(rgdal)
library(caret)
library(lubridate)
setwd("D:/Info370/teamname-v2/maps-api-test") # CHANGE TO USE OWN WD IF NEEDED
if (!require(ggmap)) { install.packages('ggmap'); require(ggmap) }
path.to.csv <- 'udistrict.csv'
spd.911 <- read.csv(path.to.csv, TRUE)

spd.911$clearance_date_ts = as.POSIXct(strptime(spd.911$Event.Clearance.Date, "%m/%d/%Y %I:%M:%S %p"))
spd.911$clearance_date_date = as.Date(spd.911$clearance_date_ts)
# View(spd.911)

uwpd.911 <- read.csv('UWPD_Data.csv', TRUE)

# 47.6560° N, 122.3095° W is Red Square
here_long <-  -122.3095
here_lat <- 47.6560

seattle = get_map(location = c(here_long, here_lat), zoom = 13, maptype = 'roadmap')
```

```{r}
spd.911 <- spd.911 %>% # Change distance column
             rowwise() %>% 
             mutate(dist=distVincentyEllipsoid(c(Longitude, Latitude), c(here_long, here_lat)))              
nrow(spd.911)

descriptions <- c("STRONG ARM ROBBERY", "PERSON WITH A WEAPON (NOT GUN)", "HAZARDS", "HARRASMENT, THREATS", "FIGHT DISTURBANCE", "CRISIS COMPLAINT - GENERAL", "ARMED ROBBERY")

data.ped <- spd.911 %>% filter(str_detect(Event.Clearance.Description, paste(descriptions, collapse="|")))
# data.ped <- data.now
nrow(data.ped)

data.now <- data.ped %>% filter(clearance_date_ts > '2016-01-01 00:00:00') # Filters data within last year
nrow(data.now)
                  
data.here <- data.now %>% filter(dist < 4600) 

data <- data.here # This is data that is from one year ago, violent crimes only, filtered to be within a certain range
nrow(data)
# View(data)

ggmap(seattle) +
   geom_point(data = data, aes(x = Longitude, y = Latitude), colour = "red", alpha = 0.75)
  #coord_map()
write.csv(data, "YearSEAPD.csv")
```

```{r}

```

```{r}
# Mutate new column giving hour of day solved. Using Event Clearance Date since time reported is unfortunately not available NOT DONE
# TODO: BIN INTO HOUR LONG SECTIONS, PLOT SMALL MULTIPLES AND ALSO ONE OVERLAPPING
data$event_clearance_ts <- as.POSIXct(strptime(data$Event.Clearance.Date, "%m/%d/%Y %I:%M:%S %p")) # Ask Jon how this works
data$event_clearance_date <- as.Date(data$event_clearance_ts)
data$event_clearance_month <- month(ymd_hms(as.character(data$event_clearance_ts)))
data$event_clearance_day <- weekdays(data$event_clearance_date)
data$event_clearance_hr <- hour(ymd_hms(as.character(data$event_clearance_ts)))
# Temporary checkpoint for now
# write.csv(data, 'Year-Partially-Cleaned.csv')

strsplit(toString(data[1, "Event.Clearance.Date"]), " ")
Split.Date.Time <- function(column) {
  
}
hours = as.POSIXct(hour(data$Event.Clearance.Date))
data <- data %>% mutate(hour = (hour(Event.Clearance.Date)))
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

